openapi: 3.0.0
info:
  title: API de Oficina Técnica - Javi
  description: Documentación de los endpoints para la gestión de servicios y presupuesto.
  version: 1.0.0

paths:
  /productos:
    get:
      summary: Obtener servicios disponibles
      responses:
        '200':
          description: Lista de servicios en formato JSON.
  /carrito:
    post:
      summary: Agregar servicio al presupuesto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre: 
                  type: string
                precio: 
                  type: number
      responses:
        '201':
          description: Artículo agregado con éxito.
  /carrito/total:
    get:
      summary: Ver el total y los artículos del carrito
      responses:
        '200':
          description: Retorna un objeto con total_compra e items_detallados.